### ISSUE TITLE
Prepare VM

### ISSUE THREAD

**Issue by RobinAmsters** [RobinAmsters/ROS_workshop#1]
Make live system from scratch on spare computer and flash image to USB
- [ ]  turtlebot3_simulations isn't building

**Comment by RobinAmsters** [comment]
despite the fake node not building, gazebo launchers do work fine

**Comment by RobinAmsters** [comment]
catkin_ws now builds fine. Image flashed to USB with respin.

**Comment by RobinAmsters** [comment]
Image did not install on PC. Will retry on a different computer to rule out hardware problems

**Comment by alibinjunaid** [comment]
Please install netifaces and hector gazebo plugins on the base image. Also add "export SVGA_VGPU10=0" to the bashrc in order for gazebo to work on virtual machine. In bashrc, ROS hostname and uri needs to be localhost for gazebo simulation.

**Comment by RobinAmsters** [comment]
TODO: 

- [ ] Save VM snapshot in stead of ISO for simplified setup
