### ISSUE TITLE
Add links between sections

### ISSUE THREAD

**Issue by ratking82** [RobinAmsters/ROS_workshop#18]
It would nice if we could reference previous sections from later in the notebook.

**Comment by RobinAmsters** [comment]
View only links can be added in a similar way to [this project](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python).

[example](http://nbviewer.jupyter.org/github/robinamsters/ROS_workshop/blob/master/tutorials/3_Hands_on_with_TB3.ipynb)

**Comment by ratking82** [comment]
Thanks! Closing
