### ISSUE TITLE
Create Wiki for workshop

### ISSUE THREAD

**Issue by ratking82** [RobinAmsters/ROS_workshop#20]
Create a wiki about the workshop that contains information about
- [ ] Installation
   - [x]  Linux (maybe ??)
   - [x] ROS Kinetic
   - [x] Jupyter Notebooks
         Maybe include info about Anaconda (or miniconda)
   - [ ] How to use the Repo
- [x] Linux basics

Please feel free to update this issue with other topics that could be included in the wiki.

**Comment by ratking82** [comment]
With reference to #22, the wiki should contain information about all extra packages the must be installed through Anaconda for the tutorials to work correctly.

**Comment by RobinAmsters** [comment]
An[ installation page](https://github.com/RobinAmsters/ROS_workshop/wiki/Software-installation) has been added to the wiki.

**Comment by RobinAmsters** [comment]
A page on [linux basics](https://github.com/RobinAmsters/ROS_workshop/wiki/Linux-basics) has been added as well.

**Comment by RobinAmsters** [comment]
How to use the repo is explained in README with #33. Closing.
