### ISSUE TITLE
Make an installation shell script

### ISSUE THREAD

**Issue by ratking82** [RobinAmsters/ROS_workshop#22]
Make an bash install script for easy installation of all required dependencies.
- [ ] Anaconda 2
- [ ] Python 
- [ ]  ROS 
- [ ] Jupyter 
- [ ] python-catkin-pkg

**Comment by RobinAmsters** [comment]
A shell script could be used as well. 
- Start with the [install_anaconda.sh](https://www.anaconda.com/download/#linux) script.

- Add dependencies with pip install for:
  - rospkg
   - catkin_pkg
   - defused_xml

- Install ROS kinetic with the script from [ROBOTIS](https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros_kinetic.sh) (adds some usefull aliases as well)

- Install additional ROS dependencies with apt-get:
  - ros-kinetic-joy 
  - ros-kinetic-teleop-twist-joy 
  - ros-kinetic-teleop-twist-keyboard 
  - ros-kinetic-laser-proc 
  - ros-kinetic-rgbd-launch 
  - ros-kinetic-depthimage-to-laserscan 
  - ros-kinetic-rosserial-arduino 
  - ros-kinetic-rosserial-python
  - ros-kinetic-rosserial-server 
  - ros-kinetic-rosserial-client
  - ros-kinetic-rosserial-msgs
  - ros-kinetic-amcl 
  - ros-kinetic-map-server 
  - ros-kinetic-move-base 
  - ros-kinetic-urdf 
  - ros-kinetic-xacro 
  - ros-kinetic-compressed-image-transport 
  - ros-kinetic-rqt-image-view 
  - ros-kinetic-gmapping 
  - ros-kinetic-navigation 
  - ros-kinetic-interactive-markers

- Add turtlebot packages to catkin workspace:
  - [turtlebot3](https://github.com/ROBOTIS-GIT/turtlebot3.git)
  - [turtlebot3_msgs](https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git)
  - [turtlebot3_simulations](https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git)

- Add ROS_workshop package to catkin workspace and ROS_workshop main files to home directory

- Add following lines to bashrc (keep hastags, will be uncommented when needed during turtlebot examples):
  - export TURTLEBOT3_MODE=burger
  - \# export ROS_MASTER_URI=http://192.168.42.4
  - \# export ROS_HOSTNAME=http://192.168.42.4

**Comment by ratking82** [comment]
I think the shell script approach might be better. Changing the name of the issue to reflect the approach. 
Note, installing Anaconda will already install Python and Jupyter Notebooks. 

Edit: Maybe the wiki should contain a page which shows how to do this manually.

**Comment by RobinAmsters** [comment]
An [installation page](https://github.com/RobinAmsters/ROS_workshop/wiki/Software-installation) has been added to the wiki. Is there still time for a shell script ?

**Comment by ratking82** [comment]
I think we donot need a shell script as we are providing an ISO. Maybe at a later date we can update the wiki by adding a page on how to install each piece of software individually.

**Comment by RobinAmsters** [comment]
An ISO is indeed even simpler. Closing.
