### ISSUE TITLE
Update raspberry pi clock when starting navigation launch file

### ISSUE THREAD

**Issue by RobinAmsters** [RobinAmsters/ROS_workshop#25]
When the clock of the raspberry pi and the pc are not synced, then DWA refuses to plan a trajectory. 

Possible fixes:
 - Connect the pi to the internet with the ethernet connector and do an ntp sync: ` sudo ntpdate ntp.ubuntu.com`
- date command, example: ` sudo date -s 'Tue Mar 6 15:36:40 CET 2018'`
- Automate date command with shell script or ROS node

**Comment by ratking82** [comment]
Addressed in PR #29 closing
