### ISSUE TITLE
PDF generation script

### ISSUE THREAD

**Issue by RobinAmsters** [RobinAmsters/ROS_workshop#30]
It would be nice if we had a script that compiled the notebooks together with some documentation from the wiki into a single PDF.

Iptyhon notebooks can be converted to pdf with [nbconvert](https://ipython.org/ipython-doc/3/notebook/nbconvert.html)

Markdown conversion could be accomplished with tools such as [markdown-pdf](https://github.com/alanshaw/markdown-pdf).

**Comment by ratking82** [comment]
I still think this is an overkill. Users can refer to the wiki itself.

**Comment by RobinAmsters** [comment]
It is indeed overkill with the addition of the wiki. Closing.
