### ISSUE TITLE
roscore occupies kernel

### ISSUE THREAD

**Issue by RobinAmsters** [RobinAmsters/ROS_workshop#6]
When a roscore command is run from inside a notebook, tjis occupies the active kernel. As a result, no code cells below it can be executed unless it is stopped first.

**Comment by ratking82** [comment]
We could start a new terminal inside Jupyter and run `roscore` from there. Then any python scripts inside a notebook that uses ROS will execute. 

Note this also means we need not depend on a bash terminal and we can present the workshop without leaving a web browser.

**Comment by RobinAmsters** [comment]
Let's use seperate browser terminals for now, and look into jupyter lab for easier terminal management.

**Comment by ratking82** [comment]
We will run `roscore` from Jupyter terminals. Closing.
