### ISSUE TITLE
Should we put tutorial related notebooks and sources in tutorial folder ?

### ISSUE THREAD

**Issue by ratking82** [RobinAmsters/ROS_workshop#8]
It may be better to store workshop related Jupyter notebooks and associated source files in a separate folder. For example,
    
    ROS_Workshop/
         catkin_workspace/
             build/
             devel/
             src/
                tutorial_package/
         tutorials/
             src/
             tutorial_1.ipynb
             ....

As we can load external python files in a notebook, the presenter can demonstrate the process of building a catkin package and copy the pre existing code into `src` folder of the package.

**Comment by RobinAmsters** [comment]
I hadn't thought of making a catkin workspace inside the repo. This looks like a much better setup than having seperate subrepo for the ros packages

**Comment by ratking82** [comment]
Just to clarify, we are not adding the catkin workspace to the repo. The catkin workspace should be created during demo.

**Comment by ratking82** [comment]
This has already been addressed in PR #16. Closing.
